export enum routes {
  DASHBOARD = '/',
  USER = '/user',
  MYTIME = '/my-time',
  WEEKLYHOUR = '/weekly-hour',
  EXPENSE = '/expense',
  TIMESHEET = '/time-sheet',
  EXPENSESHEET = '/expense-sheet',
  ADMINEXPENSE = '/admin-expense',
  INVOICE = '/invoice',
  BUDGET = '/budget',
  // EMPLOYEES = '/employees',
  COMPANY = '/company',
  PROJECT = '/project',
  TASK = '/task',
  LISTS = '/lists',
  LOGIN = '/auth/login',
  SETTING = '/setting',
  QUICKBOOKS = '/quickbooks',
  SUBSCRIPTION = '/subscription',
  COUNTRY = '/country',
  SKILLS = '/skills',
  CATEGORY = '/category',
  EMPLOYER = '/employer'
}
